/** Generated by vite-plugin-ionic-elements */

import { defineCustomElement as defineActionSheet } from '@ionic/core/components/ion-action-sheet'
import { defineCustomElement as defineAlert } from '@ionic/core/components/ion-alert'
import { defineCustomElement as defineApp } from '@ionic/core/components/ion-app'
import { defineCustomElement as defineAvatar } from '@ionic/core/components/ion-avatar'
import { defineCustomElement as defineButton } from '@ionic/core/components/ion-button'
import { defineCustomElement as defineButtons } from '@ionic/core/components/ion-buttons'
import { defineCustomElement as defineCard } from '@ionic/core/components/ion-card'
import { defineCustomElement as defineCardContent } from '@ionic/core/components/ion-card-content'
import { defineCustomElement as defineCardHeader } from '@ionic/core/components/ion-card-header'
import { defineCustomElement as defineCardSubtitle } from '@ionic/core/components/ion-card-subtitle'
import { defineCustomElement as defineCardTitle } from '@ionic/core/components/ion-card-title'
import { defineCustomElement as defineContent } from '@ionic/core/components/ion-content'
import { defineCustomElement as defineHeader } from '@ionic/core/components/ion-header'
import { defineCustomElement as defineItem } from '@ionic/core/components/ion-item'
import { defineCustomElement as defineItemDivider } from '@ionic/core/components/ion-item-divider'
import { defineCustomElement as defineItemGroup } from '@ionic/core/components/ion-item-group'
import { defineCustomElement as defineLabel } from '@ionic/core/components/ion-label'
import { defineCustomElement as defineList } from '@ionic/core/components/ion-list'
import { defineCustomElement as defineListHeader } from '@ionic/core/components/ion-list-header'
import { defineCustomElement as defineLoading } from '@ionic/core/components/ion-loading'
import { defineCustomElement as defineModal } from '@ionic/core/components/ion-modal'
import { defineCustomElement as defineNav } from '@ionic/core/components/ion-nav'
import { defineCustomElement as defineNote } from '@ionic/core/components/ion-note'
import { defineCustomElement as definePopover } from '@ionic/core/components/ion-popover'
import { defineCustomElement as defineRoute } from '@ionic/core/components/ion-route'
import { defineCustomElement as defineRouteRedirect } from '@ionic/core/components/ion-route-redirect'
import { defineCustomElement as defineRouter } from '@ionic/core/components/ion-router'
import { defineCustomElement as defineSelect } from '@ionic/core/components/ion-select'
import { defineCustomElement as defineSelectOption } from '@ionic/core/components/ion-select-option'
import { defineCustomElement as defineSpinner } from '@ionic/core/components/ion-spinner'
import { defineCustomElement as defineTab } from '@ionic/core/components/ion-tab'
import { defineCustomElement as defineTabBar } from '@ionic/core/components/ion-tab-bar'
import { defineCustomElement as defineTabButton } from '@ionic/core/components/ion-tab-button'
import { defineCustomElement as defineTabs } from '@ionic/core/components/ion-tabs'
import { defineCustomElement as defineThumbnail } from '@ionic/core/components/ion-thumbnail'
import { defineCustomElement as defineTitle } from '@ionic/core/components/ion-title'
import { defineCustomElement as defineToast } from '@ionic/core/components/ion-toast'
import { defineCustomElement as defineToggle } from '@ionic/core/components/ion-toggle'
import { defineCustomElement as defineToolbar } from '@ionic/core/components/ion-toolbar'

export const defineIonicElements = () => {
  defineActionSheet()
  defineAlert()
  defineApp()
  defineAvatar()
  defineButton()
  defineButtons()
  defineCard()
  defineCardContent()
  defineCardHeader()
  defineCardSubtitle()
  defineCardTitle()
  defineContent()
  defineHeader()
  defineItem()
  defineItemDivider()
  defineItemGroup()
  defineLabel()
  defineList()
  defineListHeader()
  defineLoading()
  defineModal()
  defineNav()
  defineNote()
  definePopover()
  defineRoute()
  defineRouteRedirect()
  defineRouter()
  defineSelect()
  defineSelectOption()
  defineSpinner()
  defineTab()
  defineTabBar()
  defineTabButton()
  defineTabs()
  defineThumbnail()
  defineTitle()
  defineToast()
  defineToggle()
  defineToolbar()
}
