/**
 * Usage:
 *  1. Import Ionic elements using tag started with "<ion-"
 *  2. The code will be updated in "ELEMENTS_DEFINING_FILE"
 */

import { pascalCase } from 'change-case'
import fs from 'fs'
import path from 'path'
import { Plugin } from 'vite'

const ELEMENTS_DEFINING_FILE = path.join(__dirname, 'define-elements.ts')

const REGEX = /(?<=<ion-)[a-z-]+/g

const toExcludes = ['icon'] as readonly string[]

const relateds = {
  select: ['alert', 'action-sheet', 'popover'],
} as const

const update = (elements: Set<string>) => {
  Object.entries(relateds).forEach(([element, relateds]) => {
    if (!elements.has(element)) return
    relateds.forEach(related => elements.add(related))
  })

  const toUpdates = [...elements].sort()
  const importings: string[] = []
  const definings: string[] = []

  toUpdates.forEach(element => {
    const defining = `define${pascalCase(element)}`
    const importing = `import { defineCustomElement as ${defining} }`
    const from = `from '@ionic/core/components/ion-${element}'`

    importings.push(`${importing} ${from}`)
    definings.push(`  ${defining}()`)
  })

  const code = [
    '/** Generated by vite-plugin-ionic-elements */\n',
    ...importings,
    '\nexport const defineIonicElements = () => {',
    ...definings,
    '}\n',
  ].join('\n')

  fs.writeFileSync(ELEMENTS_DEFINING_FILE, code)
}

export const pluginIonicElements = (): Plugin => {
  const elements = new Set<string>()
  let hasQueued = false

  return {
    name: 'ionic-elements',
    enforce: 'post',
    transform(code, id) {
      if (!/\.tsx$/.test(id)) return null

      let elementCount = elements.size
      Array.from(code.matchAll(REGEX)).forEach(([element]) => {
        if (toExcludes.includes(element)) return
        elements.add(element)
      })
      if (elements.size === elementCount || hasQueued) return

      hasQueued = true
      setTimeout(() => {
        hasQueued = false
        update(elements)
      })
    },
  }
}
